# NumPy ufuncs
## What are ufuncs?
ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.

## Why use ufuncs?
ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.

They also provide broadcasting and additional methods like reduce, accumulate etc. that are very helpful for computation.

ufuncs also take additional arguments, like:

where boolean array or condition defining where the operations should take place.

dtype defining the return type of elements.

out output array where the return value should be copied.


## What is Vectorization?
Converting iterative statements into a vector based operation is called vectorization.

It is faster as modern CPUs are optimized for such operations.

## Add the Elements of Two Lists
list 1: [1, 2, 3, 4]

list 2: [4, 5, 6, 7]

One way of doing it is to iterate over both of the lists and then sum each elements.

Without ufunc, we can use Python's built-in zip() method:

In [3]:
lst1 = [1,2,3,4,5]
lst2 = [5,6,7,8,9]
lst3 = []

for i,j in zip(lst1,lst2):
    lst3.append(i+j)

lst3

[6, 8, 10, 12, 14]

NumPy has a ufunc for this, called add(x, y) that will produce the same result.

In [4]:
import numpy as np
np.add(lst1,lst2)

array([ 6,  8, 10, 12, 14])

# Create Your Own ufunc
## How To Create Your Own ufunc
To create your own ufunc, you have to define a function, like you do with normal functions in Python, then you add it to your NumPy ufunc library with the frompyfunc() method.

### The frompyfunc() method takes the following arguments:

- function - the name of the function.
- inputs - the number of input arguments (arrays).
- outputs - the number of output arrays.

In [21]:
import numpy as np
def myadd(a,b):
    return a+b

myadd = np.frompyfunc(myadd,2,1)

myadd([1,2,3,4,5],[6,7,8,9,0])

array([7, 9, 11, 13, 5], dtype=object)

## Check if a Function is a ufunc
Check the type of a function to check if it is a ufunc or not.

A ufunc should return <class 'numpy.ufunc'>.

In [22]:
type(np.add)

numpy.ufunc

In [25]:
type(myadd)

numpy.ufunc

To test if the function is a ufunc in an if statement, use the numpy.ufunc value (or np.ufunc if you use np as an alias for numpy):

#### Example
Use an if statement to check if the function is a ufunc or not:

In [26]:


import numpy as np

if type(np.add) == np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc')

add is ufunc


# Simple Arithmetic

You could use arithmetic operators + - * / directly between NumPy arrays, but this section discusses an extension of the same where we have functions that can take any array-like objects e.g. lists, tuples etc. and perform arithmetic conditionally.

<mark>Arithmetic Conditionally: means that we can define conditions where the arithmetic operation should happen</mark>

All of the discussed arithmetic functions take a where parameter in which we can specify that condition.


## Addition
The add() function sums the content of two arrays, and return the results in a new array.

In [30]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([3,4,6,7,9,8])

np.add(arr1,arr2)

array([ 4,  6,  9, 11, 14, 14])

## Subtraction
The subtract() function subtracts the values from one array with the values from another array, and return the results in a new array.

In [31]:
np.subtract(arr1,arr2)

array([-2, -2, -3, -3, -4, -2])

## Multiplication
The multiply() function multiplies the values from one array with the values from another array, and return the results in a new array.

In [33]:
np.multiply(arr1,arr2)

array([ 3,  8, 18, 28, 45, 48])

## Division
The divide() function divides the values from one array with the values from another array, and return the results in a new array.

In [34]:
np.divide(arr1,arr2)

array([0.33333333, 0.5       , 0.5       , 0.57142857, 0.55555556,
       0.75      ])

## Power
The power() function rises the values from the first array to the power of the values of the second array, and return the results in a new array.

In [35]:
np.power(arr1,arr2)

array([      1,      16,     729,   16384, 1953125, 1679616])

## Remainder
Both the mod() and the remainder() functions return the remainder of the values in the first array corresponding to the values in the second array, and return the results in a new array.

In [36]:
np.remainder(arr1,arr2)

array([1, 2, 3, 4, 5, 6])

In [37]:
np.mod(arr1,arr2)

array([1, 2, 3, 4, 5, 6])

## Quotient and Mod
The divmod() function return both the quotient and the mod. The return value is two arrays, the first array contains the quotient and second array contains the mod.

In [38]:
np.divmod(arr1,arr2)

(array([0, 0, 0, 0, 0, 0]), array([1, 2, 3, 4, 5, 6]))

## Absolute Values
Both the absolute() and the abs() functions do the same absolute operation element-wise but we should use absolute() to avoid confusion with python's inbuilt math.abs()

In [39]:
np.absolute(arr1,arr2)

array([1, 2, 3, 4, 5, 6])

# Rounding Decimals
There are primarily five ways of rounding off decimals in NumPy:

- truncation
- fix
- rounding
- floor
- ceil

## Truncation
Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.

In [40]:
np.trunc([1.235667,2.3456755])

array([1., 2.])

In [41]:
np.fix([1.235667,2.3456755])

array([1., 2.])

## Rounding
The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.

E.g. round off to 1 decimal point, 3.16666 is 3.2

Round off 3.1666 to 2 decimal places:

In [44]:
np.round(3.16666,2)

np.float64(3.17)

## Floor
The floor() function rounds off decimal to nearest lower integer.

E.g. floor of 3.166 is 3.

In [45]:
np.floor([-3.45634,4.5675])

array([-4.,  4.])