# Numpy

## What is NumPy?
NumPy is a Python library used for working with arrays.

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.

NumPy stands for Numerical Python.

## Why Use NumPy?
In Python we have lists that serve the purpose of arrays, but they are slow to process.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

Arrays are very frequently used in data science, where speed and resources are very important.

## Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.

This behavior is called locality of reference in computer science.

This is the main reason why NumPy is faster than lists. Also it is optimized to work with latest CPU architectures.

## Which Language is NumPy written in?
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.



# Creating Arrays
Create a NumPy ndarray Object
NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

In [3]:
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

arr

array([1, 2, 3, 4, 5])

## 1-D Arrays
An array that has 0-D arrays as its elements is called uni-dimensional or 1-D array.

These are the most common and basic arrays.

In [4]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

## 2-D Arrays
An array that has 1-D arrays as its elements is called a 2-D array.

These are often used to represent matrix or 2nd order tensors.

<mark>NumPy has a whole sub module dedicated towards matrix operations called numpy.mat</mark>

In [5]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,0]])
arr

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

## 3-D arrays
An array that has 2-D arrays (matrices) as its elements is called 3-D array.

These are often used to represent a 3rd order tensor.

In [6]:
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
arr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

## Check Number of Dimensions?
NumPy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions the array have.

In [7]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


## Higher Dimensional Arrays
An array can have any number of dimensions.

When the array is created, you can define the number of dimensions by using the ndmin argument.

In [8]:
arr = np.array([1,2,3,4,5,6,7,9,0],ndmin=4)
arr.ndim

4

# NumPy Array Indexing
## Access Array Elements
Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [9]:
arr = np.array([1,2,3,4])
arr[0]

np.int64(1)

## Access 2-D Arrays
To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.

In [10]:
arr = np.array([1,2,3,4,5,6,7,9,0],ndmin=2)
arr[0,1]

np.int64(2)

## Access 3-D Arrays
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [11]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr[0,1,1]

np.int64(5)

## Example Explained
arr[0, 1, 2] prints the value 6.

And this is why:

The first number represents the first dimension, which contains two arrays:
[[1, 2, 3], [4, 5, 6]]
and:
[[7, 8, 9], [10, 11, 12]]
Since we selected 0, we are left with the first array:
[[1, 2, 3], [4, 5, 6]]

The second number represents the second dimension, which also contains two arrays:
[1, 2, 3]
and:
[4, 5, 6]
Since we selected 1, we are left with the second array:
[4, 5, 6]

The third number represents the third dimension, which contains three values:
4
5
6
Since we selected 2, we end up with the third value:
6



## Negative Indexing
Use negative indexing to access an array from the end.

In [12]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr[-1,-1,-1]

np.int64(12)

# NumPy Array Slicing
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [13]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[4:])

[5 6 7]


## Negative Slicing
Use the minus operator to refer to an index from the end:

### Example
Slice from the index 3 from the end to index 1 from the end:



In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


## STEP
Use the step value to determine the step of the slicing:



In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [17]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]



## Slicing 2-D Arrays
From the second element, slice elements from index 1 to index 4 (not included):

In [18]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[1,2:4]

array([8, 9])

In [19]:
arr[:,2]

array([3, 8])

In [20]:
arr[0:2,1:4]

array([[2, 3, 4],
       [7, 8, 9]])

# Data Types
Data Types in Python
By default Python have these data types:

- strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
- integer - used to represent integer numbers. e.g. -1, -2, -3
- float - used to represent real numbers. e.g. 1.2, 42.42
- boolean - used to represent True or False.
- complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

## Data Types in NumPy
NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string
- V - fixed chunk of memory for other type ( void )

## Checking the Data Type of an Array
The NumPy array object has a property called dtype that returns the data type of the array:

In [21]:
arr.dtype


dtype('int64')

## Creating Arrays With a Defined Data Type
We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

In [22]:
arr = np.array([1,2,3,4,5],dtype='i')
arr.dtype , arr

(dtype('int32'), array([1, 2, 3, 4, 5], dtype=int32))

#### Example
Create an array with data type 4 bytes integer:

In [23]:
arr = np.array([1,2,3,4,5],dtype='i4')
arr.dtype , arr

(dtype('int32'), array([1, 2, 3, 4, 5], dtype=int32))

### What if a Value Can Not Be Converted?
If a type is given in which elements can't be casted then NumPy will raise a ValueError.

## Converting Data Type on Existing Arrays
The best way to change the data type of an existing array, is to make a copy of the array with the astype() method.

The astype() function creates a copy of the array, and allows you to specify the data type as a parameter.

The data type can be specified using a string, like 'f' for float, 'i' for integer etc. or you can use the data type directly like float for float and int for integer.

#### Example
Change data type from float to integer by using 'i' as parameter value:

In [24]:
arr = np.array([1.1,2.3,3,4,5])
new_arr = arr.astype('i')
new_arr, new_arr.dtype

(array([1, 2, 3, 4, 5], dtype=int32), dtype('int32'))

# Array Copy vs View

## The Difference Between Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

In [25]:
arr = np.array([1,2,3,4,5])

new_arr = arr.copy()

arr[0] = 10

arr, new_arr

(array([10,  2,  3,  4,  5]), array([1, 2, 3, 4, 5]))

<mark>The copy SHOULD NOT be affected by the changes made to the original array.</mark>

## VIEW:

In [26]:
arr = np.array([1,2,3,4,5])
new_arr = arr.view()
arr[0] = 100

arr, new_arr

(array([100,   2,   3,   4,   5]), array([100,   2,   3,   4,   5]))

<mark>The view SHOULD be affected by the changes made to the original array.</mark>

<h3>Make Changes in the VIEW:</h3>

In [27]:
arr = np.array([1,2,3,4,5])
new_arr = arr.view()
new_arr[0] = 100

new_arr,arr

(array([100,   2,   3,   4,   5]), array([100,   2,   3,   4,   5]))

<mark style="padding: 4px;">The original array SHOULD be affected by the changes made to the view.</mark>


## Check if Array Owns its Data
As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [28]:
arr = np.array([1,2,3,4,5])
new_arr = arr.view()
copy_arry = arr.copy()

new_arr.base,copy_arry.base

(array([1, 2, 3, 4, 5]), None)

# Array Shape
The shape of an array is the number of elements in each dimension.

## Get the Shape of an Array
NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements

In [29]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
arr.shape

(2, 4)

The example above returns (2, 4), which means that the array has 2 dimensions, where the first dimension has 2 elements and the second has 4.

In [30]:
arr = np.array([1, 2, 3, 4], ndmin=5)
arr.shape

(1, 1, 1, 1, 4)

# Array Reshaping
Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.



In [31]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Reshape From 1-D to 3-D

In [32]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

## Can We Reshape Into any Shape?
Yes, as long as the elements required for reshaping are equal in both shapes.

We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.


## Returns Copy or View?

In [33]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
new_arr = arr.reshape(2,6)
new_arr.base,new_arr

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]))

## Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [34]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr.reshape(2,2,-1)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

<mark style= "padding: 5px;">Note: We can not pass -1 to more than one dimension.</mark>

## Flattening the arrays
Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [35]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

arr.reshape(-1)

array([1, 2, 3, 4, 5, 6])

<mark style="padding: 5px;">Note: There are a lot of functions for changing the shapes of arrays in numpy flatten, ravel and also for rearranging the elements rot90, flip, fliplr, flipud etc. These fall under Intermediate to Advanced section of numpy.</mark>

# Array Iterating

Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

In [36]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
for i in arr:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


## Iterating 2-D Arrays
In a 2-D array it will go through all the rows.

In [37]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


## Iterating 3-D Arrays
In a 3-D array it will go through all the 2-D arrays.

In [38]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for i in arr:
    print(i)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


## Iterating Arrays Using nditer()
The function nditer() is a helping function that can be used from very basic to very advanced iterations. It solves some basic issues which we face in iteration, lets go through it with examples.

### Iterating on Each Scalar Element
In basic for loops, iterating through each scalar of an array we need to use n for loops which can be difficult to write for arrays with very high dimensionality.

In [39]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


## Iterating Array With Different Data Types
We can use op_dtypes argument and pass it the expected datatype to change the datatype of elements while iterating.

NumPy does not change the data type of the element in-place (where the element is in array) so it needs some other space to perform this action, that extra space is called buffer, and in order to enable it in nditer() we pass flags=['buffered'].

In [40]:
# Iterate through the array as a string:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


## Iterating With Different Step Size
We can use filtering and followed by iteration.

In [41]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:,::2]):
    print(x)

1
3
5
7


## Enumerated Iteration Using ndenumerate()
Enumeration means mentioning sequence number of somethings one by one.

Sometimes we require corresponding index of the element while iterating, the ndenumerate() method can be used for those usecases.

In [42]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for ind,x in np.ndenumerate(arr):
    print(ind,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# Joining Array

Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

## concatenate()

In [43]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([7,8,9,10])

arr3 = np.concatenate((arr1,arr2))
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### 2D array Concatination

In [44]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr3 = np.concatenate((arr1,arr2),axis=1)
arr3

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## Joining Arrays Using Stack Functions
Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

We can concatenate two 1-D arrays along the second axis which would result in putting them one over the other, ie. stacking.

We pass a sequence of arrays that we want to join to the stack() method along with the axis. If axis is not explicitly passed it is taken as 0.

In [45]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr3 = np.stack((arr1,arr2),axis=1)
arr3

array([[1, 4],
       [2, 5],
       [3, 6]])

In [46]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr3 = np.stack((arr1,arr2))
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

<h3>Concatenate vs Stack</h3>

| Feature        | `concatenate()`                                   | `stack()`                                                  |
|----------------|---------------------------------------------------|------------------------------------------------------------|
| **Purpose**    | Joins arrays along an existing axis               | Joins arrays along a new axis                              |
| **Axis Behavior** | Uses existing axes (e.g., `axis=0` or `axis=1`) | Adds a new dimension (e.g., stacking 1D arrays into 2D)    |
| **Shape Impact** | Shape changes only along the specified axis      | Shape increases in dimensionality                          |
| **Use Case**   | Merging datasets, extending arrays                | Creating grouped structures, layering arrays               |

## Stacking Along Rows
<h4>hstack()</h4>
NumPy provides a helper function: hstack() to stack along rows.

np.hstack() stands for horizontal stack. It stacks arrays side by side, along the second axis (axis=1) for 2D arrays, or simply extends 1D arrays.

In [47]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr3 = np.hstack((arr1,arr2))
arr3

array([1, 2, 3, 4, 5, 6])

## Stacking Along Columns
### vstack() vertical stack
NumPy provides a helper function: vstack()  to stack along columns.

In [48]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr3 = np.vstack((arr1,arr2))
arr3

array([[1, 2, 3],
       [4, 5, 6]])

## Stacking Along Height (depth)
### dstack() depth stack
NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

In [49]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr3 = np.dstack((arr1,arr2))
arr3

array([[[1, 4],
        [2, 5],
        [3, 6]]])

# Splitting Array
Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.


In [50]:
arr = np.array([1,2,3,4,5,6,7,9,0])
arr2 = np.array_split(arr,3)
arr2

[array([1, 2, 3]), array([4, 5, 6]), array([7, 9, 0])]

If the array has less elements than required, it will adjust from the end accordingly.

<mark>If the array has less elements than required, it will adjust from the end accordingly.</mark>

## Split Into Arrays
The return value of the array_split() method is a list containing each of the split as an array.

If you split an array into 3 arrays, you can access them from the result just like any array element:

In [51]:
print(arr2[0]) 
print(arr2[1])
print(arr2[2])

[1 2 3]
[4 5 6]
[7 9 0]


## Splitting 2-D Arrays
Use the same syntax when splitting 2-D arrays.

Use the array_split() method, pass in the array you want to split and the number of splits you want to do.

In [52]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

arr2 = np.array_split(arr,3)
arr2

[array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]),
 array([[ 9, 10],
        [11, 12]])]

The example above returns three 2-D arrays.

In addition, you can specify which axis you want to do the split around.

The example below also returns three 2-D arrays, but they are split along the column (axis=1).

In [53]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

np.array_split(arr,3,axis=1)

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

## hstack()
An alternate solution is using hsplit() opposite of hstack()

In [54]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

np.hsplit(arr,3)

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

<mark>Note: Similar alternates to vstack() and dstack() are available as vsplit() and dsplit().</mark>

# Searching Arrays
You can search an array for a certain value, and return the indexes that get a match.

To search an array, use the where() method.

In [55]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

np.where(arr == 4)

(array([3, 5, 6]),)

In [56]:
np.where(arr%2 == 0)

(array([1, 3, 5, 6]),)

In [58]:
for i in np.where(arr%2 == 0):
    print(arr[i])

[2 4 4 4]


## Search Sorted
There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

<mark>The searchsorted() method is assumed to be used on sorted arrays.</mark>

In [67]:
arr = np.array([1, 2,7,3, 4, 5, 4,3,9,5, 4])
arr.sort()
print(arr)
np.searchsorted(arr,7)

[1 2 3 3 4 4 4 5 5 7 9]


np.int64(9)

### Search From the Right Side
By default the left most index is returned, but we can give side='right' to return the right most index instead.

In [71]:
arr = np.array([1, 2,7,3, 4, 5, 4,3,9, 4])

arr.sort()
np.searchsorted(arr,5,side='right'),arr


(np.int64(8), array([1, 2, 3, 3, 4, 4, 4, 5, 7, 9]))

# Sorting Arrays
Sorting means putting elements in an ordered sequence.

Ordered sequence is any sequence that has an order corresponding to elements, like numeric or alphabetical, ascending or descending.

The NumPy ndarray object has a function called sort(), that will sort a specified array.

In [72]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


# Filter Array
Getting some elements out of an existing array and creating a new array out of them is called filtering.

In NumPy, you filter an array using a boolean index list.

<mark>A boolean index list is a list of booleans corresponding to indexes in the array.</mark>

If the value at an index is True that element is contained in the filtered array, if the value at that index is False that element is excluded from the filtered array.


In [73]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


The example above will return [41, 43], why?

Because the new array contains only the values where the filter array had the value True, in this case, index 0 and 2.

## Creating the Filter Array
In the example above we hard-coded the True and False values, but the common use is to create a filter array based on conditions.

In [74]:
arr = np.array([41, 42, 43, 44])
filter_list = []
for n in arr:
    if n %2 == 0 :
        filter_list.append(True)
    else:
        filter_list.append(False)

arr[filter_list]


array([42, 44])

## Creating Filter Directly From Array
The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.

We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

In [76]:
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42

arr[filter_list],filter_arr

(array([42, 44]), array([False, False,  True,  True]))

In [77]:
arr = np.array([41, 42, 43, 44])

filter_arr = arr %2 == 0
arr[filter_arr]

array([42, 44])